[tool.black]
extend-exclude = '''
/ (
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | env
)/
'''

[tool.isort]
profile = "black"
[tool.flake8]
ignore = "E203,E266,E501,W503"
max-line-length = 88
max-complexity = 18
select = "B,C,E,F,W,T4,B9"